import asyncio
from datetime import datetime
from backend.crawler.parser import smart_parser
from backend.rag.chunker import semantic_chunker
from backend.rag.vector_store import KnowledgeBaseIndex

SAMPLE_SITE_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>AethelExult.AI - Neural Web Scraping & RAG Intelligence Engine</title>
    <meta name="description" content="Transform any public website into an intelligent AI assistant using deep scraping, hybrid vector databases, and grounded RAG.">
</head>
<body>
    <header><nav><a href="/">Home</a><a href="/features">Features</a></nav></header>
    <main>
        <h1>AethelExult.AI: The Future of Autonomous Website Knowledge</h1>
        <p>AethelExult.AI empowers enterprises, researchers, and developers to transform any public website into an intelligent, high-precision AI knowledge assistant. By combining asynchronous multi-page crawling, semantic DOM extraction, dense vector embeddings, and hybrid BM25 search, AethelExult.AI delivers sub-second answers grounded strictly in source documentation.</p>

        <h2>Autonomous Crawling Architecture</h2>
        <p>The AethelExult.AI scraping engine traverses internal links recursively using an asynchronous queue. It respects robots.txt directives, normalizes canonical URLs, bypasses navigational clutter, and extracts clean markdown hierarchy without cookies, banners, or ads.</p>

        <h2>Hybrid Vector Retrieval and Grounded RAG</h2>
        <p>Retrieved documents are divided into hierarchical semantic chunks with breadcrumb headers. Queries execute across both dense vector cosine similarity and sparse BM25 lexical keyword rankings. The resulting context is injected into a strictly grounded system prompt that prevents hallucinations and generates verified citations.</p>

        <h2>Supported AI Models</h2>
        <p>AethelExult.AI natively integrates Google Gemini (Gemini 2.5 Flash, Gemini 1.5 Pro, and text-embedding-004) alongside OpenAI GPT-4o, with a built-in offline local semantic synthesis engine for zero-setup exploration.</p>

        <h2>Enterprise Security and Citations</h2>
        <p>Every response generated by AethelExult.AI features interactive source attribution cards. Users can click any citation [1], [2] to inspect the exact scraped paragraph, confidence score, and original URL.</p>
    </main>
    <footer><p>© 2026 AethelExult.AI. All rights reserved.</p></footer>
</body>
</html>
"""

SAMPLE_PYTHON_DOCS_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>Python 3.12 Documentation - Built-in Types and Asynchronous I/O</title>
    <meta name="description" content="Comprehensive documentation on Python 3.12 concurrency, asyncio, and data structures.">
</head>
<body>
    <header><nav><a href="/">Docs</a></nav></header>
    <main>
        <h1>Python 3.12: Concurrency and Asyncio Framework</h1>
        <p>Python 3.12 introduces major performance improvements to asyncio event loops, sub-interpreters, and low-overhead monitoring. Asyncio provides the foundation for writing single-threaded concurrent code using coroutines, multiplexing I/O access over sockets and other resources.</p>

        <h2>Task Management and TaskGroup</h2>
        <p>The asyncio.TaskGroup context manager provides a reliable way to run a group of concurrent tasks. If any task fails with an exception, remaining tasks in the group are automatically canceled, preventing leaked background coroutines.</p>

        <h2>Coroutines and Event Loops</h2>
        <p>Coroutines declared with async def syntax are executed by scheduling them on an event loop or awaiting them inside another coroutine. The event loop is the core of every asyncio application.</p>

        <h2>Performance Enhancements</h2>
        <p>Python 3.12 features optimized function calls, specialized adaptive bytecode (PEP 659), and reduced memory consumption for dictionaries and object instances.</p>
    </main>
    <footer><p>Python Software Foundation</p></footer>
</body>
</html>
"""

SAMPLE_APPLE_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>Apple - Hardware, Software, Services and Innovation</title>
    <meta name="description" content="Discover the innovative world of Apple: iPhone, Mac, iPad, Apple Watch, and AI services.">
</head>
<body>
    <header><nav><a href="/">Store</a><a href="/mac">Mac</a><a href="/iphone">iPhone</a></nav></header>
    <main>
        <h1>Apple Inc: Flagship Products and Services</h1>
        <p>Apple designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories, and sells a variety of related services. Flagship hardware lines include the iPhone, Mac personal computers (MacBook Pro, MacBook Air, iMac, Mac Studio), iPad tablets, and the Apple Watch wearable series.</p>

        <h2>iPhone Product Family</h2>
        <p>The iPhone product family represents Apple's premier smartphone lineup, featuring cutting-edge Apple Silicon A-series processors, Super Retina XDR OLED displays, Ceramic Shield protection, and advanced multi-lens camera systems with optical image stabilization and ProRes video recording.</p>

        <h2>Mac Computers and Apple Silicon</h2>
        <p>Apple Silicon (M-series processors including M3, M4, and M4 Pro) powers the Mac ecosystem, delivering industry-leading performance-per-watt, unified memory architecture, and extended battery life across MacBook Air and MacBook Pro.</p>

        <h2>Apple Services and Subscription Platforms</h2>
        <p>Apple's services portfolio encompasses the App Store, Apple Music, Apple TV+, Apple Pay, iCloud+, and Apple Care, providing seamless cloud storage, entertainment, and digital payments across Apple devices.</p>
    </main>
    <footer><p>Copyright © 2026 Apple Inc. All rights reserved.</p></footer>
</body>
</html>
"""

SAMPLE_OPENAI_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>OpenAI - Research, GPT-4o, ChatGPT and Artificial Intelligence</title>
    <meta name="description" content="OpenAI research and deployment company developing safe and beneficial AGI.">
</head>
<body>
    <header><nav><a href="/">Research</a><a href="/products">Products</a></nav></header>
    <main>
        <h1>OpenAI: Advancing Safe Artificial General Intelligence</h1>
        <p>OpenAI conducts frontier AI research and develops leading foundational models. Flagship offerings include ChatGPT, GPT-4o, GPT-4o mini, DALL-E 3 image generation, and the OpenAI API for developers worldwide.</p>

        <h2>GPT-4o Multimodal Intelligence</h2>
        <p>GPT-4o ('omni') natively accepts text, audio, and image inputs and generates text, audio, and visual outputs with real-time responsiveness and human-like conversational fluency across diverse languages and domains.</p>

        <h2>ChatGPT Enterprise and Team Capabilities</h2>
        <p>ChatGPT Enterprise delivers enterprise-grade security, data privacy, administrative console controls, and dedicated high-speed access to advanced reasoning and custom GPT models.</p>

        <h2>Developer API and Fine-Tuning</h2>
        <p>The OpenAI API allows developers to integrate text completion, chat, embeddings, structured outputs, and vision capabilities into applications with fine-tuning and retrieval assistance.</p>
    </main>
    <footer><p>© 2026 OpenAI. All rights reserved.</p></footer>
</body>
</html>
"""

SAMPLE_INFOMEISTER_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>INFOMEISTER 2.0 - Futuristic Student Tech Association</title>
    <meta name="description" content="Official platform for INFOMEISTER, the Computer Science and AI Association of INFO Institute of Engineering.">
</head>
<body>
    <header><nav><a href="/">Home</a><a href="/about">About</a><a href="/domains">Domains</a><a href="/events">Events</a><a href="/contact">Contact</a></nav></header>
    <main>
        <h1>INFOMEISTER 2.0: United by Passion, Driven by Excellence</h1>
        <p>INFOMEISTER is a high-performance student technology association at INFO Institute of Engineering dedicated to hands-on engineering, product development, and career-ready skills. Founded in 2025, INFOMEISTER has impacted over 500+ students across 35+ technical events and 40+ specialized workshops.</p>

        <h2>Master Core Technical Domains</h2>
        <p>INFOMEISTER's ecosystem is structured across 6 core technical domains, each led by dedicated domain leads, mentors, and practical project tracks:</p>
        <ul>
            <li><strong>AI & Machine Learning</strong>: Deep learning, Natural Language Processing (NLP), Computer Vision, neural networks, and deploying production ML models.</li>
            <li><strong>Full-Stack Development</strong>: Modern frontend frameworks (React, Next.js), backend microservices, robust REST/GraphQL APIs, database architecture, and cross-platform mobile apps.</li>
            <li><strong>DevOps & Cloud Computing</strong>: AWS, Google Cloud Platform, Docker containerization, Kubernetes orchestration, CI/CD automated pipelines, and Infrastructure as Code.</li>
            <li><strong>Product & UI/UX Design</strong>: Design thinking methodologies, user research, wireframing, high-fidelity Figma prototyping, and product design systems.</li>
            <li><strong>Data Engineering & Analytics</strong>: Distributed data pipelines, big data architectures (Spark, Kafka), data warehousing, advanced SQL, and predictive analytics dashboards.</li>
            <li><strong>Cybersecurity & Ethical Hacking</strong>: Network security defense, penetration testing, threat modeling, cryptography, vulnerability assessment, and secure code practices.</li>
        </ul>

        <h2>Flagship Events & Trisquadathon 2.0</h2>
        <p>INFOMEISTER hosts premier competitive technical gatherings, hackathons, and symposiums:</p>
        <p><strong>Trisquadathon 2.0</strong> is INFOMEISTER's flagship 3-track technical hackathon and multi-domain innovation marathon, uniting students from across institutions to solve real-world industry problem statements with substantial prize pools, industry mentorship, and sponsorship opportunities.</p>
        <p>Other regular events include hands-on technical bootcamps, code sprints, open-source workshops, and guest lectures from Silicon Valley and global industry leaders.</p>

        <h2>Faculty Leadership and Staff Coordinators</h2>
        <p>INFOMEISTER operates under the esteemed guidance of experienced academic advisors and faculty mentors:</p>
        <p><strong>Dr. Gokila M</strong> serves as the Faculty Coordinator (Associate Professor, Department of Artificial Intelligence and Data Science). Dr. Gokila provides strategic direction, research mentorship, and event coordination.</p>
        <p>The association is supported jointly by the Department of Computer Science and Engineering and the Department of Artificial Intelligence and Data Science at INFO Institute of Engineering.</p>

        <h2>Impact Metrics and Milestones</h2>
        <p>Since its founding in 2025, INFOMEISTER has achieved measurable milestones:</p>
        <ul>
            <li>500+ Active Student Members and Participants</li>
            <li>35+ Successfully Executed Technical Events</li>
            <li>40+ Deep-Dive Practical Workshops and Hackathons</li>
            <li>Active collaborative Discord and developer community</li>
        </ul>
    </main>
    <footer><p>© 2026 INFOMEISTER. All rights reserved.</p></footer>
</body>
</html>
"""


async def seed():
    sites = [
        ("kb_aethelexult_ai", "https://aethelexult.ai", "aethelexult.ai", "AethelExult.AI - Neural Knowledge Engine", SAMPLE_SITE_HTML),
        ("kb_docs_python_org", "https://docs.python.org/3", "docs.python.org", "Python 3.12 Documentation", SAMPLE_PYTHON_DOCS_HTML),
        ("kb_www_apple_com", "https://www.apple.com", "apple.com", "Apple - Hardware, Software & Services", SAMPLE_APPLE_HTML),
        ("kb_openai_com", "https://openai.com", "openai.com", "OpenAI - Research & Frontier Models", SAMPLE_OPENAI_HTML),
        ("kb_www_infomeister_co_in", "https://www.infomeister.co.in", "www.infomeister.co.in", "INFOMEISTER 2.0 - Student Tech Community", SAMPLE_INFOMEISTER_HTML),
    ]

    for kb_id, url, domain, title, html in sites:
        doc = smart_parser.parse(html, url)
        chunks = semantic_chunker.chunk_page(doc)
        kb = KnowledgeBaseIndex(kb_id)
        await kb.build(
            metadata={
                "kb_id": kb_id,
                "url": url,
                "domain": domain,
                "title": title,
                "description": doc.get("description", ""),
                "total_pages": 1,
                "total_chunks": len(chunks),
                "total_words": doc["word_count"],
                "created_at": datetime.now().isoformat(),
                "last_crawled_at": datetime.now().isoformat(),
                "pages": [{"url": doc["url"], "title": doc["title"], "word_count": doc["word_count"], "depth": 0}],
                "crawl_tree": [{"url": doc["url"], "title": doc["title"], "parent": None, "depth": 0, "word_count": doc["word_count"]}]
            },
            chunks=chunks,
            provider="local"
        )
        print(f"Populated {kb_id} ({len(chunks)} chunks)")

    print("All initial seed knowledge bases successfully populated!")


if __name__ == "__main__":
    asyncio.run(seed())
