"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Layers,
  FileText,
  Clock,
  Sparkles,
  Search,
  Download,
  Trash2,
  RefreshCw,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  Tag,
  BookOpen,
} from "lucide-react";
import {
  KnowledgeBaseMetadata,
  ChunkItem,
  AnalyticsResponse,
  api,
} from "@/lib/api";

interface KnowledgeHUDProps {
  currentKb: KnowledgeBaseMetadata | null;
  onRefreshKbList: () => void;
  onDeleteKb: (kbId: string) => void;
}

export const KnowledgeHUD: React.FC<KnowledgeHUDProps> = ({
  currentKb,
  onRefreshKbList,
  onDeleteKb,
}) => {
  const [analytics, setAnalytics] = useState<AnalyticsResponse | null>(null);
  const [loadingAnalytics, setLoadingAnalytics] = useState(false);
  const [chunks, setChunks] = useState<ChunkItem[]>([]);
  const [loadingChunks, setLoadingChunks] = useState(false);
  const [chunkSearch, setChunkSearch] = useState("");
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);
  const [selectedChunk, setSelectedChunk] = useState<ChunkItem | null>(null);

  useEffect(() => {
    if (currentKb) {
      loadAnalytics(currentKb.kb_id);
      loadChunks(currentKb.kb_id);
    }
  }, [currentKb?.kb_id]);

  const loadAnalytics = async (kbId: string) => {
    setLoadingAnalytics(true);
    try {
      const data = await api.getAnalytics(kbId);
      setAnalytics(data);
    } catch (e) {
      console.error("Error loading analytics:", e);
    } finally {
      setLoadingAnalytics(false);
    }
  };

  const loadChunks = async (kbId: string, search?: string) => {
    setLoadingChunks(true);
    try {
      const res = await api.getChunks(kbId, search, 30, 0);
      setChunks(res.chunks);
    } catch (e) {
      console.error("Error loading chunks:", e);
    } finally {
      setLoadingChunks(false);
    }
  };

  const handleSearchChunks = (e: React.FormEvent) => {
    e.preventDefault();
    if (currentKb) {
      loadChunks(currentKb.kb_id, chunkSearch);
    }
  };

  if (!currentKb) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16 text-center">
        <div className="p-8 rounded-2xl bg-slate-900/60 border border-white/[0.08] backdrop-blur-xl">
          <Layers className="w-10 h-10 text-cyan-400/60 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-slate-200 mb-2">No Website Selected</h3>
          <p className="text-sm text-slate-400 max-w-md mx-auto">
            Please crawl a website or select one from the navigation dropdown to inspect its vector metrics, topic clusters, and auto-generated FAQs.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
      {/* Top Banner & Quick Actions */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-white/[0.08] backdrop-blur-xl flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-xl">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
              KNOWLEDGE BASE ID: {currentKb.kb_id}
            </span>
            <span className="text-xs font-mono text-slate-400">
              Crawled: {new Date(currentKb.created_at).toLocaleDateString()}
            </span>
          </div>
          <h2 className="text-2xl font-bold text-white flex items-center gap-2">
            <span>{currentKb.title || currentKb.domain}</span>
            <a
              href={currentKb.url}
              target="_blank"
              rel="noreferrer"
              className="text-slate-400 hover:text-cyan-400"
            >
              <ExternalLink className="w-4 h-4" />
            </a>
          </h2>
          <p className="text-xs text-slate-400 mt-1 max-w-xl">
            {currentKb.description || "Structured semantic knowledge base generated by AethelExult.AI."}
          </p>
        </div>

        <div className="flex items-center gap-2 self-start md:self-center">
          <a
            href={api.getExportUrl(currentKb.kb_id, "json")}
            download
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-mono text-slate-200 transition-all"
            title="Download JSON"
          >
            <Download className="w-3.5 h-3.5" />
            <span>JSON</span>
          </a>

          <a
            href={api.getExportUrl(currentKb.kb_id, "markdown")}
            download
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-mono text-slate-200 transition-all"
            title="Download Markdown"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Markdown</span>
          </a>

          <button
            onClick={() => {
              if (confirm(`Are you sure you want to delete the knowledge base for ${currentKb.domain}?`)) {
                onDeleteKb(currentKb.kb_id);
              }
            }}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-rose-500/10 hover:bg-rose-500/20 text-rose-300 border border-rose-500/20 text-xs font-mono transition-all"
            title="Delete KB"
          >
            <Trash2 className="w-3.5 h-3.5" />
            <span>Delete</span>
          </button>
        </div>
      </div>

      {/* KPI Stats HUD Grid with Motion Hover */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <motion.div
          whileHover={{ y: -4, scale: 1.02 }}
          transition={{ type: "spring", stiffness: 400, damping: 25 }}
          className="p-4 rounded-xl bg-slate-900/70 border border-cyan-500/20 hover:border-cyan-500/40 shadow-[0_0_20px_rgba(0,240,255,0.08)] transition-colors cursor-default"
        >
          <div className="flex items-center justify-between text-slate-400 mb-1">
            <span className="text-xs font-mono">Total Pages</span>
            <BookOpen className="w-4 h-4 text-cyan-400" />
          </div>
          <p className="text-2xl font-bold text-white">{currentKb.total_pages}</p>
          <span className="text-[10px] text-cyan-400/80 font-mono">Verified Internal URLs</span>
        </motion.div>

        <motion.div
          whileHover={{ y: -4, scale: 1.02 }}
          transition={{ type: "spring", stiffness: 400, damping: 25 }}
          className="p-4 rounded-xl bg-slate-900/70 border border-purple-500/20 hover:border-purple-500/40 shadow-[0_0_20px_rgba(139,92,246,0.08)] transition-colors cursor-default"
        >
          <div className="flex items-center justify-between text-slate-400 mb-1">
            <span className="text-xs font-mono">Document Chunks</span>
            <Layers className="w-4 h-4 text-purple-400" />
          </div>
          <p className="text-2xl font-bold text-white">{currentKb.total_chunks}</p>
          <span className="text-[10px] text-purple-400/80 font-mono">Hierarchical Sections</span>
        </motion.div>

        <motion.div
          whileHover={{ y: -4, scale: 1.02 }}
          transition={{ type: "spring", stiffness: 400, damping: 25 }}
          className="p-4 rounded-xl bg-slate-900/70 border border-emerald-500/20 hover:border-emerald-500/40 shadow-[0_0_20px_rgba(16,185,129,0.08)] transition-colors cursor-default"
        >
          <div className="flex items-center justify-between text-slate-400 mb-1">
            <span className="text-xs font-mono">Total Words</span>
            <FileText className="w-4 h-4 text-emerald-400" />
          </div>
          <p className="text-2xl font-bold text-white">{currentKb.total_words.toLocaleString()}</p>
          <span className="text-[10px] text-emerald-400/80 font-mono">Clean Extracted Text</span>
        </motion.div>

        <motion.div
          whileHover={{ y: -4, scale: 1.02 }}
          transition={{ type: "spring", stiffness: 400, damping: 25 }}
          className="p-4 rounded-xl bg-slate-900/70 border border-blue-500/20 hover:border-blue-500/40 shadow-[0_0_20px_rgba(59,130,246,0.08)] transition-colors cursor-default"
        >
          <div className="flex items-center justify-between text-slate-400 mb-1">
            <span className="text-xs font-mono">Est. Reading Time</span>
            <Clock className="w-4 h-4 text-blue-400" />
          </div>
          <p className="text-2xl font-bold text-white">
            {analytics?.statistics.reading_time_min || Math.max(1, Math.round(currentKb.total_words / 200))} min
          </p>
          <span className="text-[10px] text-blue-400/80 font-mono">Dense Knowledge Index</span>
        </motion.div>
      </div>

      {/* Auto-Generated Summary & Key Insights */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left 2 Cols: Executive Summary */}
        <div className="lg:col-span-2 p-6 rounded-2xl bg-slate-900/80 border border-white/[0.08] backdrop-blur-xl">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-cyan-400" />
              <h3 className="font-bold text-base text-white">Executive Website Summary</h3>
            </div>
            <button
              onClick={() => loadAnalytics(currentKb.kb_id)}
              disabled={loadingAnalytics}
              className="text-xs font-mono text-slate-400 hover:text-cyan-300 flex items-center gap-1 cursor-pointer"
            >
              <RefreshCw className={`w-3 h-3 ${loadingAnalytics ? "animate-spin" : ""}`} />
              <span>Refresh</span>
            </button>
          </div>

          <div className="text-xs sm:text-sm text-slate-300 leading-relaxed font-sans min-h-[80px]">
            {loadingAnalytics ? (
              <div className="flex items-center gap-2 text-slate-500 italic py-6">
                <div className="w-4 h-4 border-2 border-cyan-400/30 border-t-cyan-400 rounded-full animate-spin" />
                <span>Synthesizing website analytics and entity map...</span>
              </div>
            ) : analytics?.summary ? (
              <p className="whitespace-pre-wrap">{analytics.summary}</p>
            ) : (
              <p className="text-slate-500 italic">No summary generated yet.</p>
            )}
          </div>

          {/* Key Insights */}
          <div className="mt-6 pt-4 border-t border-white/[0.06]">
            <h4 className="text-xs font-mono text-cyan-400 uppercase tracking-wider mb-3">Key Strategic Insights</h4>
            <div className="space-y-2">
              {analytics?.insights.map((insight, idx) => (
                <div key={idx} className="flex items-start gap-2.5 text-xs text-slate-300">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
                  <span>{insight}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Col: Topic Clusters & Keywords */}
        <div className="p-6 rounded-2xl bg-slate-900/80 border border-white/[0.08] backdrop-blur-xl flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-4">
              <Tag className="w-4 h-4 text-purple-400" />
              <h3 className="font-bold text-base text-white">Topic Clusters</h3>
            </div>

            <div className="flex flex-wrap gap-2 mb-6">
              {analytics?.topics.map((t, idx) => (
                <motion.div
                  key={idx}
                  whileHover={{ scale: 1.05 }}
                  className="px-2.5 py-1 rounded-lg bg-purple-500/10 border border-purple-500/20 text-xs font-mono text-purple-200 flex items-center gap-1.5 cursor-default"
                >
                  <span>{t.name}</span>
                  <span className="text-[10px] text-purple-400 font-bold">{Math.round(t.relevance * 100)}%</span>
                </motion.div>
              ))}
            </div>

            {/* Keyword tags */}
            {analytics?.statistics.top_keywords && (
              <div>
                <h4 className="text-xs font-mono text-slate-400 mb-2">High Frequency Entities:</h4>
                <div className="flex flex-wrap gap-1.5">
                  {analytics.statistics.top_keywords.map((kw, i) => (
                    <span
                      key={i}
                      className="px-2 py-0.5 rounded bg-slate-800 text-[11px] font-mono text-slate-300 border border-slate-700"
                    >
                      #{kw}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="mt-6 pt-4 border-t border-white/[0.06] text-[11px] text-slate-400 font-mono">
            Hybrid Vector Engine: BM25 + Dense Cosine
          </div>
        </div>
      </div>

      {/* Auto-Generated FAQs Accordion */}
      {analytics?.faqs && analytics.faqs.length > 0 && (
        <div className="p-6 rounded-2xl bg-slate-900/80 border border-white/[0.08] backdrop-blur-xl shadow-xl">
          <div className="flex items-center gap-2 mb-4">
            <Sparkles className="w-4 h-4 text-emerald-400" />
            <h3 className="font-bold text-base text-white">Auto-Generated Website FAQs</h3>
          </div>

          <div className="space-y-2">
            {analytics.faqs.map((faq, idx) => {
              const isOpen = expandedFaq === idx;
              return (
                <div
                  key={idx}
                  className="rounded-xl border border-white/[0.06] bg-slate-950/60 overflow-hidden transition-all"
                >
                  <button
                    onClick={() => setExpandedFaq(isOpen ? null : idx)}
                    className="w-full flex items-center justify-between p-4 text-left text-xs font-semibold text-slate-200 hover:text-cyan-300 transition-colors cursor-pointer"
                  >
                    <span>{faq.question}</span>
                    {isOpen ? <ChevronUp className="w-4 h-4 shrink-0 text-cyan-400" /> : <ChevronDown className="w-4 h-4 shrink-0 text-slate-400" />}
                  </button>
                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.25, ease: "easeInOut" }}
                        className="overflow-hidden"
                      >
                        <div className="px-4 pb-4 pt-1 text-xs text-slate-400 leading-relaxed border-t border-white/[0.04]">
                          {faq.answer}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Document Chunk Explorer */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-white/[0.08] backdrop-blur-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
          <div className="flex items-center gap-2">
            <Layers className="w-4 h-4 text-cyan-400" />
            <h3 className="font-bold text-base text-white">Document Chunk Explorer</h3>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-400">
              {chunks.length} chunks loaded
            </span>
          </div>

          <form onSubmit={handleSearchChunks} className="flex items-center gap-2">
            <div className="relative">
              <input
                type="text"
                value={chunkSearch}
                onChange={(e) => setChunkSearch(e.target.value)}
                placeholder="Filter chunks by keyword..."
                className="pl-8 pr-3 py-1.5 text-xs bg-slate-950 border border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400"
              />
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
            </div>
            <button
              type="submit"
              className="px-3 py-1.5 rounded-lg bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 text-xs font-mono hover:bg-cyan-500/30 transition-all"
            >
              Filter
            </button>
          </form>
        </div>

        {/* Chunks List */}
        <div className="space-y-2 max-h-96 overflow-y-auto pr-1">
          {loadingChunks ? (
            <div className="py-8 text-center text-slate-500 italic">Loading indexed chunks...</div>
          ) : chunks.length === 0 ? (
            <div className="py-8 text-center text-slate-500 italic">No chunks match your search query.</div>
          ) : (
            chunks.map((chunk) => (
              <div
                key={chunk.chunk_id}
                onClick={() => setSelectedChunk(chunk)}
                className="p-3 rounded-xl bg-slate-950/60 hover:bg-slate-800/80 border border-white/[0.04] hover:border-cyan-500/30 transition-all cursor-pointer flex items-center justify-between gap-4"
              >
                <div className="truncate">
                  <div className="flex items-center gap-2 text-[11px] font-mono mb-1">
                    <span className="text-cyan-400">{chunk.chunk_id}</span>
                    <span className="text-slate-500">•</span>
                    <span className="text-slate-300 font-semibold">{chunk.section_heading || "Overview"}</span>
                  </div>
                  <p className="text-xs text-slate-400 truncate">{chunk.raw_text || chunk.text}</p>
                </div>
                <div className="text-right shrink-0">
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-400">
                    {chunk.token_count} tokens
                  </span>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Chunk Detail Drawer */}
      {selectedChunk && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4">
          <div className="max-w-xl w-full p-6 rounded-2xl bg-slate-900 border border-cyan-500/40 shadow-2xl">
            <div className="flex items-center justify-between mb-4 pb-3 border-b border-white/[0.08]">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono font-bold text-cyan-400">
                  {selectedChunk.chunk_id}
                </span>
                <span className="text-xs font-mono text-slate-400">
                  ({selectedChunk.token_count} tokens)
                </span>
              </div>
              <button
                onClick={() => setSelectedChunk(null)}
                className="text-xs font-mono text-slate-400 hover:text-white px-2 py-1 rounded bg-slate-800"
              >
                Close
              </button>
            </div>

            <h4 className="text-sm font-bold text-white mb-1">{selectedChunk.title}</h4>
            <p className="text-xs text-cyan-400 font-mono mb-4">{selectedChunk.section_heading}</p>

            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-300 font-mono leading-relaxed max-h-72 overflow-y-auto whitespace-pre-wrap">
              {selectedChunk.text}
            </div>

            <div className="mt-4 flex items-center justify-between">
              <a
                href={selectedChunk.url}
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1.5 text-xs text-cyan-400 hover:underline font-mono"
              >
                <span>Open Source Page</span>
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(selectedChunk.text);
                  alert("Chunk copied!");
                }}
                className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-mono text-slate-300"
              >
                Copy Chunk
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
